name: heroku-deploy

on:
  push:
    branches: 
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.4.6
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "inventory-control-of-dep-ui"
          heroku_email: "pshyshkavets@gmail.com"
    - name: Run script
      run: echo successfully run
